site_name: ""
site_author: Kieran Lowe
site_description: ""
site_url: https://kieran-lowe.github.io/""/
repo_name: ""
repo_url: ""
edit_uri: edit/main/docs
copyright: Kieran Lowe

plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  icon:
    repo: fontawesome/brands/github
  features:
    - content.action.edit
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.expand
    - navigation.top
    - navigation.sections
    - toc.integrate
    - toc.follow
  palette:
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Light Mode
extra: 
  homepage: https://kieranlowe.io
nav:
  - Home: index.md

